name: "FTP Deploy"
description: ""
inputs:
  env-type:
    description: "Env Type"
    required: false
    default: 'sftp'
  env-host:
    description: "Env Host"
    required: true
    default: ''
  env-port:
    description: "Env Port"
    required: true
    default: ''
  env-user:
    description: "Env User"
    required: true
    default: ''
  env-pass:
    description: "Env Password"
    required: true
    default: ''
  env-remote-root:
    description: "Env Remote Root"
    required: true
    default: ''
  env-local-root:
    description: "Env Local Root"
    required: true
    default: ''
  manifest:
    description: "Manifest of files to upload/remove"
    required: true
    default: ''
  force-ignore:
    description: "Ignore files on deployment"
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Setup Rclone
      shell: bash
      run: |
        curl https://rclone.org/install.sh | sudo bash

        SECURE_PASS=$(echo "${{ inputs.env-pass }}" | rclone obscure -)

        mkdir -p "$HOME/.config/rclone"
        {
          echo "[remote]"
          echo "type = ${{ inputs.env-type }}"
          echo "host = ${{ inputs.env-host }}"
          echo "port = ${{ inputs.env-port }}"
          echo "user = ${{ inputs.env-user }}"
          echo "pass = ${SECURE_PASS}"
        } > "$HOME/.config/rclone/rclone.conf"

        rclone mkdir "remote:${{ inputs.env-remote-root }}"

        mkdir -p "${GITHUB_WORKSPACE}/remote"

        rclone mount "remote:${{ inputs.env-remote-root }}" "${GITHUB_WORKSPACE}/remote" --daemon --allow-other

        ls "${GITHUB_WORKSPACE}/remote"

        echo "test" > "${GITHUB_WORKSPACE}/remote/file"

        ls "${GITHUB_WORKSPACE}/remote"


