name: "FTP Deploy"
description: ""
inputs:
  env-type:
    description: "Env Type"
    required: false
    default: 'sftp'
  env-host:
    description: "Env Host"
    required: true
    default: ''
  env-port:
    description: "Env Port"
    required: true
    default: ''
  env-user:
    description: "Env User"
    required: true
    default: ''
  env-pass:
    description: "Env Password"
    required: true
    default: ''
  env-remote-root:
    description: "Env Remote Root"
    required: true
    default: ''
  env-local-root:
    description: "Env Local Root"
    required: true
    default: ''
  manifest:
    description: "Manifest of files to upload/remove"
    required: true
    default: ''
  force-ignore:
    description: "Ignore files on deployment"
    required: false
    default: ''
  concurrent-connections:
    description: "Concurrent connections"
    required: false
    default: '20'
runs:
  using: "composite"
  steps:
    - name: Setup Rclone
      shell: bash
      run: |
        echo "::group::Installing rclone"
        curl https://rclone.org/install.sh | sudo bash
        echo "::endgroup::"

    - name: Run upload
      shell: bash
      env:
        INPUT_ENV_TYPE: ${{ inputs.env-type }}
        INPUT_ENV_HOST: ${{ inputs.env-host }}
        INPUT_ENV_PORT: ${{ inputs.env-port }}
        INPUT_ENV_USER: ${{ inputs.env-user }}
        INPUT_ENV_PASS: ${{ inputs.env-pass }}
        INPUT_ENV_REMOTE_ROOT: ${{ inputs.env-remote-root }}
        INPUT_ENV_LOCAL_ROOT: ${{ inputs.env-local-root }}
        INPUT_FORCE_IGNORE: ${{ inputs.force-ignore }}
        INPUT_MANIFEST: ${{ inputs.manifest }}
        INPUT_CONCURRENT_CONNECTIONS: ${{ inputs.concurrent-connections }}
      run: "${{ github.action_path }}/run.sh"

    - uses: actions/upload-artifact@v3
      with:
        name: rclone.log
        path: ${{ github.workspace }}/rclone.log
